// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAgP9E4B14DB-0uCv31uRfl5hph9_jx_U',
    appId: '1:695807288527:web:fb5163aebb3607e6e3c3ba',
    messagingSenderId: '695807288527',
    projectId: 'first-auth-f0e41',
    authDomain: 'first-auth-f0e41.firebaseapp.com',
    storageBucket: 'first-auth-f0e41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrLWu8W-VSddAw7xviJrW6t5OsbjnknDE',
    appId: '1:695807288527:android:511a98cf1f3c6277e3c3ba',
    messagingSenderId: '695807288527',
    projectId: 'first-auth-f0e41',
    storageBucket: 'first-auth-f0e41.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAgP9E4B14DB-0uCv31uRfl5hph9_jx_U',
    appId: '1:695807288527:web:eeffc2316ea640abe3c3ba',
    messagingSenderId: '695807288527',
    projectId: 'first-auth-f0e41',
    authDomain: 'first-auth-f0e41.firebaseapp.com',
    storageBucket: 'first-auth-f0e41.firebasestorage.app',
  );
}
