// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChcOg_N-wDq3Kl7i0ztK-3cDbtjEj-b5I',
    appId: '1:106217002366:web:a49d521db04893bfe90f2f',
    messagingSenderId: '106217002366',
    projectId: 'veterinary-12a3e',
    authDomain: 'veterinary-12a3e.firebaseapp.com',
    storageBucket: 'veterinary-12a3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJFABth1U6PW2r_hNYLRELhZsscsnQEw',
    appId: '1:106217002366:android:2046f1de9ca88e36e90f2f',
    messagingSenderId: '106217002366',
    projectId: 'veterinary-12a3e',
    storageBucket: 'veterinary-12a3e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChcOg_N-wDq3Kl7i0ztK-3cDbtjEj-b5I',
    appId: '1:106217002366:web:baaa372bb1511bfbe90f2f',
    messagingSenderId: '106217002366',
    projectId: 'veterinary-12a3e',
    authDomain: 'veterinary-12a3e.firebaseapp.com',
    storageBucket: 'veterinary-12a3e.firebasestorage.app',
  );
}
